---
# build.yml

- name: Build Configurations and Documentation # (1)!
  hosts: ATD_LAB
  gather_facts: false
  tasks:

    - name: Generate AVD Structured Configurations and Fabric Documentation # (2)!
      tags: [build]
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate Device Configurations and Documentation # (3)!
      tags: [build]
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Build ACT Topology
      import_role:
        name: act_topology_gen
      vars:
        non_fabric_nodes:
