---
# build.yml

- name: Build Configurations and Documentation # (1)!
  hosts: FABRIC
  gather_facts: false

  vars:
    # Adjust the output dirs to keep Digital Twin artifacts in a separate directory
    output_dir_name: "digital_twin/intended"
    documentation_dir_name: "digital_twin/documentation"
    # Set this flag to True to enable Digital Twin mode
    avd_digital_twin_mode: true
    
  tasks:

    - name: Generate AVD Structured Configurations and Fabric Documentation # (2)!
      tags: [build]
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate Device Configurations and Documentation # (3)!
      tags: [build]
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
