- name: "add cert"
  hosts: all
  connection: local
  gather_facts: false

  vars:
    ansible_ssh_pass: arista123
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_user: cvpadmin
    ansible_password: arista123

  tasks:
    - name: Copy CV onboarding token
      net_put:
          src: "./xyz.crt"
          dest: "/tmp/xyz.crt"
          
    - name: shut no shut terminattr
      arista.eos.eos_command:
        commands:
          - command: "enable"
          - command: "copy file:/tmp/xyz.crt certificate:xyz.crt"
