---

- name: Deploy Configs
  hosts: FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_skip_missing_devices: true
        cv_verify_certs: false
        cv_server: www.cv-staging.corp.arista.io
        cv_token: 